//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  serviceTimes: ServiceTimes;
  serviceTimesConnection: ServiceTimesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceTimesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceTimesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceTimesFilter>;
};

export type DocumentFilter = {
  serviceTimes?: InputMaybe<ServiceTimesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = ServiceTimes | Folder;

export type ServiceTimes = Node & Document & {
  __typename?: 'ServiceTimes';
  first: Scalars['String']['output'];
  second: Scalars['String']['output'];
  third: Scalars['String']['output'];
  stream: Scalars['String']['output'];
  runthrough: Scalars['String']['output'];
  runthroughEnd: Scalars['String']['output'];
  firstServiceClasses?: Maybe<Scalars['String']['output']>;
  otherServiceClasses?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiceTimesFilter = {
  first?: InputMaybe<StringFilter>;
  second?: InputMaybe<StringFilter>;
  third?: InputMaybe<StringFilter>;
  stream?: InputMaybe<StringFilter>;
  runthrough?: InputMaybe<StringFilter>;
  runthroughEnd?: InputMaybe<StringFilter>;
  firstServiceClasses?: InputMaybe<StringFilter>;
  otherServiceClasses?: InputMaybe<StringFilter>;
};

export type ServiceTimesConnectionEdges = {
  __typename?: 'ServiceTimesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ServiceTimes>;
};

export type ServiceTimesConnection = Connection & {
  __typename?: 'ServiceTimesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceTimesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateServiceTimes: ServiceTimes;
  createServiceTimes: ServiceTimes;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateServiceTimesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceTimesMutation;
};


export type MutationCreateServiceTimesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceTimesMutation;
};

export type DocumentUpdateMutation = {
  serviceTimes?: InputMaybe<ServiceTimesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  serviceTimes?: InputMaybe<ServiceTimesMutation>;
};

export type ServiceTimesMutation = {
  first?: InputMaybe<Scalars['String']['input']>;
  second?: InputMaybe<Scalars['String']['input']>;
  third?: InputMaybe<Scalars['String']['input']>;
  stream?: InputMaybe<Scalars['String']['input']>;
  runthrough?: InputMaybe<Scalars['String']['input']>;
  runthroughEnd?: InputMaybe<Scalars['String']['input']>;
  firstServiceClasses?: InputMaybe<Scalars['String']['input']>;
  otherServiceClasses?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceTimesPartsFragment = { __typename: 'ServiceTimes', first: string, second: string, third: string, stream: string, runthrough: string, runthroughEnd: string, firstServiceClasses?: string | null, otherServiceClasses?: string | null };

export type ServiceTimesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceTimesQuery = { __typename?: 'Query', serviceTimes: { __typename: 'ServiceTimes', id: string, first: string, second: string, third: string, stream: string, runthrough: string, runthroughEnd: string, firstServiceClasses?: string | null, otherServiceClasses?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceTimesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceTimesFilter>;
}>;


export type ServiceTimesConnectionQuery = { __typename?: 'Query', serviceTimesConnection: { __typename?: 'ServiceTimesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceTimesConnectionEdges', cursor: string, node?: { __typename: 'ServiceTimes', id: string, first: string, second: string, third: string, stream: string, runthrough: string, runthroughEnd: string, firstServiceClasses?: string | null, otherServiceClasses?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ServiceTimesPartsFragmentDoc = gql`
    fragment ServiceTimesParts on ServiceTimes {
  __typename
  first
  second
  third
  stream
  runthrough
  runthroughEnd
  firstServiceClasses
  otherServiceClasses
}
    `;
export const ServiceTimesDocument = gql`
    query serviceTimes($relativePath: String!) {
  serviceTimes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceTimesParts
  }
}
    ${ServiceTimesPartsFragmentDoc}`;
export const ServiceTimesConnectionDocument = gql`
    query serviceTimesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceTimesFilter) {
  serviceTimesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceTimesParts
      }
    }
  }
}
    ${ServiceTimesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      serviceTimes(variables: ServiceTimesQueryVariables, options?: C): Promise<{data: ServiceTimesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceTimesQueryVariables, query: string}> {
        return requester<{data: ServiceTimesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceTimesQueryVariables, query: string}, ServiceTimesQueryVariables>(ServiceTimesDocument, variables, options);
      },
    serviceTimesConnection(variables?: ServiceTimesConnectionQueryVariables, options?: C): Promise<{data: ServiceTimesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceTimesConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceTimesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceTimesConnectionQueryVariables, query: string}, ServiceTimesConnectionQueryVariables>(ServiceTimesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  